---
# tasks file for sosreport

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install sosreport
  ansible.builtin.package:
    name: "{{ sosreport_packages }}"
    state: present

- name: Create remote directory
  ansible.builtin.file:
    path: "{{ sosreport_remote_location }}"
    state: directory
    mode: "0755"

- name: Find sosreports before generated
  ansible.builtin.find:
    paths: "{{ sosreport_remote_location }}"
    patterns: "{{ sosreport_patterns }}"
  register: sosreport_find_sosreports_before

- name: Generate sosreport
  become: true
  ansible.builtin.command:
    cmd: "{{ sosreport_command }}"
  changed_when: true

- name: Create local directory
  ansible.builtin.file:
    path: "{{ sosreport_local_location }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  run_once: true
  become: false

- name: Find sosreports after running
  register: sosreport_find_sosreport_after
  ansible.builtin.find:
    paths: "{{ sosreport_remote_location }}"
    patterns: "{{ sosreport_patterns }}"

- name: Get the new generated sos report name
  set_fact:
    latest_reports: "{{ sosreport_find_sosreport_after.files | difference(sosreport_find_sosreports_before.files) }}"

- name: Fetch sosreports
  become: true
  loop: "{{ latest_reports }}"
  when:
    - latest_reports is defined
    - latest_reports | length >= 1
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ sosreport_local_location }}/"
    flat: true
